### ISSUE TITLE
Official announcement that Gitpan is back

### ISSUE THREAD

**Issue by oalders** [evalEmpire/gitpan#125]
@neilbowers mentioned this would be a good idea. http://neilb.org/2014/11/29/pr-challenge-2015.html#comment-1759026071

**Comment by schwern** [comment]
Go ahead!

**Comment by ribasushi** [comment]
@oalders how close is this to reality? The front page of https://github.com/gitpan looks rather outdated: is some sort of job malfunctioning?

**Comment by oalders** [comment]
@ribasushi I wish I could give some helpful info on this.  I don't know where this code is deployed or how often it is run or if it's broken etc.  @schwern did some preliminary work so that we could, at some point, integrate it into MetaCPAN but as far as I can tell, we're not close to completion there.  I would say at this point that has stalled. I should probably close this issue.

It would be helpful for MetaCPAN to generate the repos as it does the indexing.  Now that we're using a queue for the indexing work, it actually would be much less complicated to do this.
