### ISSUE TITLE
Link to use.perl post is 404

### ISSUE THREAD

**Issue by DrHyde** [evalEmpire/gitpan#127]
The link to use.perl in README.md is broken. If it can be resurrected it would be good if the content could be put into the gitpan project wiki.

**Comment by schwern** [comment]
I think I have a backup of that post somewhere...

**Comment by DrHyde** [comment]
Found it in the google cache

http://webcache.googleusercontent.com/search?q=cache:XBQvU6OHkuYJ:use.perl.org/use.perl.org/_schwern/journal/39974.html+&cd=3&hl=en&ct=clnk&gl=uk

(in case that link expires, i searched for schwern/journal/39974)

**Comment by book** [comment]
Here's the currently working link: <http://use.perl.org/use.perl.org/_schwern/journal/39974.html>.

When use.perl was turned into a static web site, most URL broke down. There's an easy mapping, though, as seen in the above example.

@arc and I worked on supporting both the old and "new" URL, by [patching](https://github.com/arc/useperl/) [WWW::UsePerl::Server](https://metacpan.org/pod/WWW::UsePerl::Server) during the [Perl QA Hackathon in Lancaster](http://act.qa-hackathon.org/qa2013/). I think the only missing bit is actually getting hold of the use.perl.org domain to point it at a server running that code.
