### ISSUE TITLE
Net::DNS is outdated

### ISSUE THREAD

**Issue by ttyS4** [evalEmpire/gitpan#133]
Hi,

I am chasing a bug in Net::DNS and if you could update it (it is 2 years old now) that would help me to run git blame and stuff.

Do not know how much work is this...

Regards,
 Tamas

**Comment by oalders** [comment]
Hi Tamas,

I don't think I have permissions to update the module, but you can do it quite easily.

```sh
cpanm Git::CPAN::Patch
git-cpan clone Net::DNS
```

Should be quite fast once the module has been installed.

Best,

Olaf
